[Design] 모여락 상세에 노출 할 모여락 상태 라벨 UI를 제작합니다.
extreme-rock/GetARock-iOS pull request #122
Opened 2023-02-14 13:32 UTC by GODNOEL

## 관련 이슈
 
- #84 

<br>

## 배경

모여락 상세에 노출 할 모여락 상태 라벨 UI를 제작합니다.

 | 구분 | D-Day | 상태 | 카테고리 | 
  |:---|:---:|:---:|:---:|
  | 이미지  | <img width="138" alt="image" src="https://user-images.githubusercontent.com/103012104/218304245-4c11256d-9f7e-41b9-81b8-367bcfb87b0e.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/103012104/218304264-e47b90b1-d159-46a2-94c3-438fdf6c06a3.png"> | <img width="259" alt="image" src="https://user-images.githubusercontent.com/103012104/218304291-e16d78f6-531d-4c16-9c05-f192f6a45827.png"> | 

<br>

## 작업 내용

### 📢 모여락 상세에 노출 할 모여락 상태 라벨이 모여있는 StackUI를 제작했습니다.

<br>

### 1️⃣ Event Data 구조 수정
- label에서 사용되는 `category`, `state`, `startTime, endTime`를 추가했습니다.

https://github.com/extreme-rock/GetARock-iOS/blob/72d244d746162a68563e5b1001e3c2b16a128d2b/GetARock/GetARock/Global/Network/Model/Event.swift#L9-L34

 | 구분 | EventState | EventCategory | 
  |:---|:---:|:---:| 
| value  | <img width="400" alt="image" src="https://user-images.githubusercontent.com/103012104/218747751-edde6b01-31c4-427c-b6e8-f6f6ef2c7293.png"> | <img width="400" alt="image" src="https://user-images.githubusercontent.com/103012104/218747799-6ff1f114-ff80-4be3-b9a7-5a3de4cea215.png"> | 

<br>

### 2️⃣ EventStateLabelStackView
-  StackVIew는 `D-Day Label`, `state Label`, `category Label` 라벨로 구성되어 있습니다.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/103012104/218745253-c765a319-433a-4ed8-999c-24006d0d394d.png">

<br>

### 3️⃣ EventStateLabel
- EventStateLabel은 `.dday`, `.state`, `.category` 3가지 타입으로 분기처리되며 각 라벨의 특성은 다음과 같습니다.

#### 👉 1. `.dday` 
- 현재 날짜로 부터 모여락 이벤트까지의 D-Day를 계산해서 보여주는 라벨입니다.
    -  날짜가 지나면 라벨이 `D-Day Label`이 삭제되도록 구현했습니다.
         - 이를 위해 DeleteDdayLabelDelegate를 제작했습니다.  
         - days가 음수가되면 StackView에서  `D-Day Label`은 삭제됩니다.
         
https://github.com/extreme-rock/GetARock-iOS/blob/72d244d746162a68563e5b1001e3c2b16a128d2b/GetARock/GetARock/Global/UIComponent/EventStateLabel.swift#L90-L108

<br>

#### 👉 2 `.state`  
- 모여락 상태를 보여주는 라벨입니다.
    -  `모집중`, `진행중`일 때는 라벨 기본 UI, `완료`,`취소`일때는 비활성화 UI를 제공합니다.
   
https://github.com/extreme-rock/GetARock-iOS/blob/72d244d746162a68563e5b1001e3c2b16a128d2b/GetARock/GetARock/Global/UIComponent/EventStateLabel.swift#L108-L126

<br>

#### 👉 3 `.category`  
- 모여락 카테고리를 보여주는 라벨입니다.
    -  각 카테고리별 title이 세팅됩니다.
    
   https://github.com/extreme-rock/GetARock-iOS/blob/72d244d746162a68563e5b1001e3c2b16a128d2b/GetARock/GetARock/Global/UIComponent/EventStateLabel.swift#L126-L136

<br>

## 리뷰 노트

- `setEventStateLabel()` 메소드가 IF문으로 케이스마다 도는것같아 보다 효율적인 코드가 있으면 말씀부탁드려요🥹
- `D-Day` 라벨 날짜가 지나면 삭제하도록 제작을 했는데 괜찮은가요?
    - 사실 없애지 않고 날짜 지나면 비활성화 UI로 노출하는 방향으로 구현했는데 
    - Int의 경우 음수는 `-`를 못없애는것 같더라구요..? (그래서 `D+-N`으로 표현되었습니다..)
    - 그래서 생각해봣는데 모여락이 지난 경우 D-Day가 중요한 정보는 아닌것같아 삭제처리하였습니다.
- 변수명이 적절한지
- 공통컴포넌트로 적절한지
- 개선해야할 코드가 있는지

<br>

## 테스트 방법
#### `LandingViewController`에 아래의 코드를 붙여넣어주세요
- `category: EventCategory.bandRecruiting`, `state: EventState.open`, `startTime:"2023-02-12 15:45:00"`의 값을 변경해서 각 상황에 적절한 라벨이 나오는지 확인해주세요!
```
class LandingViewController: UIViewController {

    let testData =  Event(name: "이벤트1",
                          category: EventCategory.bandRecruiting,
                          state: EventState.open,
                          location: Location(
                            name: "밴드1",
                            address: "대한민국 대구광역시 중구 대신동 291-61",
                            additionalAddress: "2층",
                            coordinate: Coordinate(latitude: 35.86677, longitude: 128.57930)),
                          startTime:"2023-02-12 15:45:00",
                          endTime: "2023-02-21 18:45:00"
                         )
    
    lazy var test = EventStateLabelStackView(data: testData)
    
     override func viewDidLoad() {
         super.viewDidLoad()
         view.addSubview(test)
         test.constraint(centerY:view.centerYAnchor)
         test.constraint(centerX: view.centerXAnchor)
     }

 }
```

## 스크린샷
 | 구분 |  날짜 안 지난 이벤트 | 날짜 지난 이벤트 |  
  |:---|:---:|:---:|
  | 이미지  | <img width="250" alt="image" src="https://user-images.githubusercontent.com/103012104/218753138-cf331660-12d3-43aa-a22a-cd071c18ecc7.png"> | <img width="250" alt="image" src="https://user-images.githubusercontent.com/103012104/218753209-77ba12a6-c35f-41ab-92fc-c415d22f9035.png"> |

2023-02-15 10:11 UTC, Rookie0031 requested changes
## 고생하셨습니다~ 👍

컴포넌트가 아직 남앗군요 감사합니다!!
전체적으로는 상수인데 변수로 선언된 부분은 없는지, 카멜케이스가 지켜지지않은 부분이 있는지 확인 좀 부탁드리겠습니다~

2023-02-15 10:11 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +    private  func CalculateDday() {
p3;

함수의 맨앞이 대문자로 되어있습니다!

2023-02-15 10:11 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +        case dday
p3;

dday 변수명이 이상한거 같아 고민해도 적당한게 잘 안떠오르네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 개발자들 집단 지성이 필요하겟네요
남아있는날짜니까 영어로 그냥 하면 remainingDayForEvent 로 너무 길어지는 거 같은데 좀 고민을 해야할거같네요 

아니면 차라리 이런 특수케이스에는 Dday 같은 네이밍은 어떤지??

2023-02-15 10:34 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +    private  func CalculateDday() {
하핫..항상 체크하고 내는데 죄송합니다 🥺
52b037a975fb809e84b232c8548df60d79333801

2023-02-16 06:03 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +        case dday
저도 해당 변수명에 대해 계속 고민하다가 `dday`,`dDay`,`Dday` 중에 엄청 고민하다가
`Dday`는 컨벤션을 너무 어기는것같아 `dDay`으로 작성해서 사용하던 중 뭔가 인지부조화가 와서 
`dday`로 변경했는데 지금 생각해보니 이게 컨벤션도 안맞고 제일 이상한것같네요

`Dday`, `dDay` 중 하나로 변경하고 싶은데 뭐가 나으신가요?

2023-02-16 23:56 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +        case dday
저는 원래 쓰는 규약을 따라서 dDay로 그냥 하는거도 나쁘지않아보입니다!

참고로 chatgpt 형님께서 추천해주신 목록들 입니다 ㅋㅋ..
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103009135/219514459-9025d900-6121-4e82-a78a-717fcb1c2df7.png">

2023-02-17 02:43 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +        case dday
오옷 역시  chatgpt 형님...!
루키형님 말씀대로 제일 직관적이고 컨벤션을 잘지킨 `dDay`로 수정햇습니다!

497b88c43e93ee76770a945c9eac0a3bc179bd1a

2023-02-17 13:28 UTC, GODNOEL reviewed
### 🛠️ D-day 날짜계산을 수정했습니다. @ccdkk  

데이크가 제가 구현한 D-Day 계산이 제대로 되고있지않다는 피드백을 주셔서 수정을 진행했습니다.
fb4682ebbaa4416be002dde7fc5d08b69a307c6c

<br/>

### 🚨 문제상황 
문제는 이벤트가 18일에 열리면 18일 당일 00시에 `D-0`으로 바뀌어야하는데,
지금은 현재시간이 이벤트 시간로 부터 24시간 이내에 들어오면 `D-0`으로 바뀐다는 것이였습니다.

예를들어 이벤트가 18일 11시 35분에 열리면, 17일 11시 36분 부터는 `D-0`으로 바뀐다는 것이죠..
D-Day는 시간기준이 아닌 날짜 기준으로 17일`D-1`에서 18일로 넘어가는 00시가되면 `D-0`표시로 바뀌어야합니다..

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/103012104/219661472-4b88dfdf-aefb-40c0-a3b8-941aa66c949e.png">

<br/>

### 해결방법

calendar.dateComponents([.day] ...) 메소드를 사용해도 24시간으로 계산되어 기존과 동일하게 작동해서

```
 guard let dDay = calendar.dateComponents([.day],
                                                 from: currentDay,
                                                 to:  eventDay).day else { return }
    }
```

현재날짜와 이벤트날짜에서 뒤의 `시:분:초`를 잘라 `년월일`만 
Date 형태로 만들어 calendar.dateComponents([.day] ...) 메소드에 넣음으로써
00시 기준으로 날짜의 사이가 계산될 수 있도록 수정했습니다.
구현을 위해 아래의 메소드가 추가되었습니다.

#### 👉 추가 메소드
① `toString()` : Date -> String로 변환해주는 메소드
② `extractDay()` : String으로 된 날짜(년월일 시분초)에서 시분초를 자르고 년월일만 추출해 Date 타입으로 변환

#### 👉 수정코드
```
 private func calculateDday() {
        
        //① 현재 날짜에서 시간을 제거하기 위해 문자열로 만듦
        let currentDate = Date().toString()
        //② 문자열이된 현재 날짜에서 시간을 제거히고(년월일 00시 00분) 다시 Date로 만듦
        guard let today = currentDate.extractDay() else { return }
        //③ 이벤트 날짜에서 시간을 제거하고(년월일 00시 00분) Date로 만듦
        guard let eventDay = labelData.extractDay() else { return }
        
        let calendar = Calendar.current
        guard let betweenDays = calendar.dateComponents([.day],
                                                 from: today,
                                                 to:  eventDay).day else { return }
        
        days = betweenDays
  }
```

<br/>

### 결과
현재시간이 이벤트시간의 24시를 넘어가도 1일 남았다고 보여주고 있습니다
<img width="365" alt="image" src="https://user-images.githubusercontent.com/103012104/219665937-bc7d5f74-fe07-47bf-a0a7-0138132637f9.png">

2023-02-18 04:56 UTC, ccdkk commented
@GODNOEL 
맞아요 저 from to 를 사용할 때 입력되는 Date 값이 시간을 포함하고 있다면 기존처럼 계산이 되더라구요.
그래서 노엘이 구현하신 방법처럼 string으로 바꿨다가 다시 잘라서 Date로 바꿔주는 방법이랑 그냥 day값만 빼와서 빼는 방법을 생각했었어요.
전자의 방법은 노엘이 해주신 방법 그대로네요! 멋집니다..
후자는 아래 코드 처럼 day값만 따로따로 가져와서 연산해주는 방법으로 생각했었습니다.
```Swift
   Calendar.current.dateComponents([.day], from: eventDay)
        Calendar.current.dateComponents([.day], from: currentDay)
```

지금 방법도 좋아요!
근데 아직도 아리송한게 Date()가 print찍을 때는 세계 표준시(?)로 나오지만 view에서 출력될 때는 그 나라의 timeZone에 맞춰진다고
하거든요? 저 프린트 찍히는 표준시가 우리나라보다 9시간 느린데(현재시간이 13시이면 print에는 4시로 찍힘). 계산 시점에서는 9시간 전 타임으로 계산이 되다보니,, 뭔가 그 차이로 인해 발생하는 문제는 없을지 고민이 되네요..
예를 들면 우리나라가 2월 18일 02시 인경우 Date()는 2월17일 17시일 테니까 
저 Calendar.current.dataComponents 에서 차이가 있을 수 있지 않을까.. 싶은데.. 이걸 테스트 하려면 새벽 타임이어야 해서 ㅋㅋ
제가 오늘 확인해보겠습니다..

뭔가 말이 길어질 것 같아서 게더에서 피드백을 했는데 들어주셔서 감사합니다..

2023-02-18 16:53 UTC, GODNOEL commented
데이크 아래 커밋에 수정내용 반영했습니다!
자세한 논의 및 변동사항은 추후 기록해놓겟씁니다..! 
도와주셔서 감사합니다! 🥹🥹🥹🥹

 a7e9dd5c91228df4b536d2c4817b1abcc3e628e8

2023-02-19 11:28 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/EventStateLabelStackView.swift
> +    func DeleteDdayLabel() {
p3;

함수 맨 앞에 대문자로 되어있어요!

2023-02-19 11:40 UTC, Rookie0031 approved these changes
## 고생하셨습니다 ~ 👍

데이크가 꼼꼼한 리뷰를 해주셧네요 잘봤습니다!! 
참고로 테스트 코드에 enum을 쓰실 때 enum이름까지 다 쓰시는거같은데 아래처럼 case만 적어주셔도 됩니다! 

    let testData =  Event(name: "이벤트1",
                          category: .bandRecruiting,
                          state: .open,

2023-02-20 04:52 UTC, ccdkk approved these changes
고생하셨어요!
Calendar를 상세히 다루려니 굉장히 어렵네요 ㅜㅜ 
어려운 부분 맡아주셔서 감사합니다~

2023-02-20 04:52 UTC, ccdkk commented on GetARock/GetARock.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = KBPH295XX9;
p2;
팀제거 부탁드려요!

2023-02-20 04:52 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +
오오 이런식으로 UILabel의 내부 layout을 잡아줄 수 있군요..
drawText와 contentSize에서 잡아주는 layout은 어떤 차이가 있는건가요?

2023-02-20 04:52 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/EventStateLabelStackView.swift
> +    // MARK: - VIew
p3;
주석 오타 수정 부탁드려요!

2023-02-20 05:21 UTC, compuTasha commented on GetARock/GetARock/Global/Extension/String+Extension.swift
>      func checkStringExpression() -> Bool{
p2;

MARK 주석 위아래로는 개행 추가해주세요!

2023-02-20 05:21 UTC, compuTasha commented on GetARock/GetARock/Global/Extension/String+Extension.swift
> +    func toDate() -> Date? {
p2;

여기도 MARK 주석 위아래로는 개행 추가해주세요!

2023-02-20 05:22 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +
p3;

특별한 이유가 없다면 변수 선언 사이에 개행 삭제 부탁드립니다...!

2023-02-20 05:31 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +    }
p4;

함수 네이밍을 `setActiveUI()` or `setEnabledUI()` / `SetDisabledUI()`로 변경하는 건 어떨까요..?!
기본 UI 보다는 활성화된 UI가 적절한 것 같아 조심스레.. 이야기해봅니다...

2023-02-20 06:08 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabelStackView.swift
> +    func DeleteDdayLabel() {
아 죄송합니다.. 계속 실수하네요ㅠㅠ
수정했습니다!
ae826ca02e05b6fb0638d3f75b5e5cade8fdf4c4

2023-02-20 06:11 UTC, GODNOEL commented on GetARock/GetARock.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = KBPH295XX9;
앗 감사합니다! 반영했습니다

97c083e437bc6e526e7ccd6ad83d9a6fd50436b0

2023-02-20 06:13 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabelStackView.swift
> +    // MARK: - VIew
수정햇습니다! 

4419cfcccbf2f6c986ee49f9105246d02bef298f

2023-02-20 06:14 UTC, GODNOEL commented on GetARock/GetARock/Global/Extension/String+Extension.swift
>      func checkStringExpression() -> Bool{
수정했습니다.

4419cfcccbf2f6c986ee49f9105246d02bef298f

2023-02-20 06:14 UTC, GODNOEL commented on GetARock/GetARock/Global/Extension/String+Extension.swift
> +    func toDate() -> Date? {
수정했습니다.

4419cfcccbf2f6c986ee49f9105246d02bef298f

2023-02-20 06:14 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +
수정했습니다.

4419cfcccbf2f6c986ee49f9105246d02bef298f

2023-02-20 06:17 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +    }
넵 setActiveUI() / SetDisabledUI() 으로 수정했습니다.
좋은 변수명 추천 감사합니다.

faa124ccd9fe3a08b265bd70cda40e5e01254c25

2023-02-20 06:34 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/EventStateLabel.swift
> +
### 개요
라벨의 레이아웃을 잡을때 UIView위에 Label을 얹지않고 UILabel으로만 구현하고 싶었음

<br/>

### 📐 drawText(in:) 메소드
 -  label의 text가 생성될때, rect에 관한 값을 조절하고 싶을때 사용 
 - 해당 메소드를 override하여 사용해야함 
 - rawText(in:)에서 padding값 설정해서 넣어줌
<img width="600" alt="image" src="https://user-images.githubusercontent.com/103012104/220028719-673637d3-265b-4237-9694-094c2c442a13.png">

https://developer.apple.com/documentation/uikit/uilabel/1620527-drawtext/

<br/>

### 🛠️ intrinsicContentSize 재정의
- 대부분의 view(UILabel, UIButton 등)은 기본적으로 컨텐츠 크기만큼의 intrinsic Content Size를 가지고 있음
- padding을 변경한다고 intrinsicContentSize가 변경되지 않아서 재정의 필요
- 기존의 super.intrinsicContentSize에 Padding 만큼의 높이(패딩상+하), 너비(패딩 좌+우)를 적용해주는 것!

<br/>

### 결론
drawText(in:) 은 패딩값을 설정해주는 작업이고,   contentSize는 그 값을  intrinsicContentSize에 반영하는 작업

<br/>

참고 블로그
https://ios-development.tistory.com/698

2023-02-21 05:32 UTC, compuTasha approved these changes
고생하셨습니다!!
코멘트로 수정 내용을 깔끔하게 정리해주셔서 빠르게 이해할 수 있었습니다!! 엄지척  

![image](https://user-images.githubusercontent.com/51108729/220256064-db24b6ec-61de-419e-9069-36da62184bae.png)

2023-02-21 05:33 UTC, merged