[Feat] 서버로부터 밴드의 댓글을 GET하고 작성한 댓글을 POST하는 기능을 구현했습니다.
extreme-rock/GetARock-iOS pull request #146
Opened 2023-03-01 11:38 UTC by GODNOEL

## 관련 이슈
- close #78

<br/>

## 배경
 ### 📢 댓글 UI 제작 후 서버와 연동하는 작업을 진행했습니다.

<br/>

## 작업 내용
 ### 📢 서버로부터 밴드의 댓글을 GET하고 작성한 댓글을 POST하는 기능을 구현했습니다.

<br/>

### 1️⃣ BandDetailViewController 구조
- BandDetailViewController에서 CommentListView까지의 구조는 아래와 같습니다.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/103012104/222117094-357b41dd-fd86-4d70-bc43-521965dacc35.png">

<br/>

### 2️⃣ BandInformationVO struct 제작
- 현재 밴드 생성시 POST할때 사용하는 BandInformationDTO 구조와 밴드 정보를 GET할때의 JSON 파일의 형태가 달라 `BandInformationVO`를 제작했습니다.
- 겹치는 항목들은 루키 @Rookie0031 와 상의 끝에 VO용을 따로 제작하기로 했습니다.

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/Network/Model/BandInformationVO.swift#L12-L28

<br/>

### 3️⃣ Band Data GET
-  BandDetailViewControlle에서 서버로 부터 밴드 정보를 받아와 해당 정보를 하위 뷰들에게 전달해줍니다.
- 밴드 정보를 GET할때 파라미터로 해당 밴드의 Id만 요구하기때문에 URLQueryItem를 이용해 ID값을 보냅니다.
- [참고] 현재는 서버에 밴드를 만들어서 해당 밴드의 ID값을 넣었지만 추후 지도에서 선택한 밴드의 ID값이 들어가도록 수정되어야합니다.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/103012104/222131357-aafcd338-81a2-4e59-84af-77dee44a1427.png">

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift#L78-L99

#### 👉 DetailContentView layout 
~~- 밴드 정보를 GET한 후 그 정보를 바탕으로 댓글리스트가 그려져야하기때문에 Task 코드 안에 레이아웃 코드를 넣었습니다.~~
###  @ccdkk 의 리뷰로 Task 코드 밖에 넣어도 잘 작동 되는것을 확인해 수정했습니다 

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift#L47-L75

<br/>

### 4️⃣ Band Comment POST
#### 👉  POST 정보
<img width="500" alt="image" src="https://user-images.githubusercontent.com/103012104/222122994-d9115ebe-9bad-4e5b-911f-5b61b64c2933.png">

- 댓글을 POST 할때는 Json파일을 인코딩해서 보내는 것이 아니라 `memberId`, `bandId`,  `content` 각 값을 파라미터로 보내야함
① 각 값을 담을 수 있는 변수를 생성 (추후 로그인정보와 지도로부터 각 값을 받아 넣어야함)

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift#L19-L23

② URLQueryItem를 이용해 URL에 필요한 파라미터를 담은 후 서버에 POST합니다.
https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift#L219-L260

<br/>

### 5️⃣  CommentListView의 TableView에 POST 댓글 반영
- 여기서 많이 헤멧는데 결론을 말하자면 `Delegate` 패턴이 아닌 `NotificationCenter`을 이용해서 문제를 해결했습니다.
- 도움을 주신 알로라 @compuTasha  감사합니다. 아래 노션페이지에서 자세한 정리를 보실 수 있습니다.
- 관련 노션 : https://fascinated-neem-285.notion.site/7db7dd57e48b4613bc5102abe9e5bf27

<br/>

#### 🤔 왜 `Delegate` 패턴은 안되고  `NotificationCenter` 될까?
- `NotificationCenter`이 작동됐던 이유는 두 View의 연관성이 없었기 때문이아닐까 싶습니다.
> NotificationCenter로 데이터를 전달하는 경우 : 두 VIew가 전혀연관성이 없는(화면전환을 햇거나, VC-Cell 관계가 아니라 정말 서로 떨어져있는) 객체들끼리 데이터를 전달할 때 사용하는 방식
> 출처 : https://hellozo0.tistory.com/365

#### ① WriteCommentTextView
- post 시   await BandDetailViewController().getBandData()를 실행

#### ② BandDetailViewController의 bandData didSet
- didSet에서 notification post
- userInfo에는 딕셔너리 타입이 들어가야 한다고 해서 딕셔너리 변수 만들어 전달

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift#L16-L41

#### ③ CommentListView
- Init 함수에 observer 추가 후 실행할 함수 추가
 
 https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/UIComponent/CommentListView.swift#L47-L61

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/UIComponent/CommentListView.swift#L129-L136
<br/>

## 리뷰 노트
- 변수명이 올바른지
- 더 효율적인 구현 방법 있는지
- 오타가 있는지
- 더 필요한 처리가 있는지

<br/>

## 테스트 방법
`feature/78-comment-list-server-connection` 브랜치에서 테스트해주세요!
진입점을 아래와 같이 변경해주세요 
```
window.rootViewController = BandDetailViewController()
```

만약 밴드 정보 GET에 실패한다면 서버에 테스트 밴드가 사라저셔일수도 있으니
포스트맨으로 새로운 밴드를 하나 생성해주신 후에 해당 밴드와 멤버의 id값으로 아래 변수들을 변경해주세요!

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift#L15

https://github.com/extreme-rock/GetARock-iOS/blob/73e1650fdd1aeebf64dd255e343699d0108bf1a9/GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift#L19-L22

* 백앤드 노션을 참고하셔서 만들어주세요~
https://www.notion.so/BackEnd-API-Examples-e8f0053dcdeb4b41ab5116eab65e6b33?pvs=4

<br/>

## 스크린샷
![댓글](https://user-images.githubusercontent.com/103012104/222127548-d8cec315-2d61-46a0-abe7-1008cacd59c3.gif)

2023-03-02 02:13 UTC, Rookie0031 requested changes
## 고생하셨습니다! 👍

댓글작업이 빡센데도 잘 구현해주셧네요 굿!! 👍

그런데 제가 실기기로 테스트했을 때는 등록버튼을 눌러도 UI가 업데이트가 되지않던데 다른분들은 어떠신가요???

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        NotificationCenter.default.addObserver(
p5;

옵저버 등록은 함수를 따로해서 처리하는게 어떨까요?? 그냥 가독성이 좀 더 좋아질거같아요!

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
p3;
1초의 시간간격을 두는 이유는 무엇인가요??

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    @objc func refreshTable(refresh: UIRefreshControl) {
p5;

objc 함수는 보통 유저의 행위가 이름에 들어가더라구요 ex. didTapButton( )
그래서 `didScrollDownCommentTable(sender: UIRegreshControl)` 과 같은 네이밍은 어떨까합니다!

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +    @objc func TapAddCommentButton() {
p5;

didTapAddCommentButton 네이밍은 어떨까요???

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +extension WriteCommentTextView {
p3;

현재 네트워크 함수들이 VC의 extension으로 정의되었는데 네트워크 함수도 따로관리할겸 + VC가 커지는걸 막기위해서 네트워크 폴더로 함수를 이전하는게어떨까요???

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            view.addSubview(bandTopInfoView)
p2;

레이아웃 코드는 setupLayout 함수로 따로 빼서 넣어주는게 좋을 것 같습니다!!

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
p3;

포스트 과정에서 get함수는 왜 쓰이는건가요??

2023-03-02 02:13 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                "Notion-Version": "2022-06-28",
p5;
header에 불필요한 정보가 있네요 노션 버전과 Authorization은 삭제해주셔도됩니다! 
데이크가 잘 정리해준 글을 참고해도 좋을거같아요! [Post정리](https://dolomite-governor-e25.notion.site/POST-Request-9d3bc74516564f3ca59c9a254ceedb68)

2023-03-02 03:07 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        NotificationCenter.default.addObserver(
넵 반영했습니다!
c268f820812add6be16d0385f0800f523cdb372e

2023-03-02 03:09 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
refreshControl의 애니메이션 때문에 1초의 시간 간격을 두었습니다!
시간 간격을 두지않으면 refreshControl이 애니메이션 되는 동안 목록이 올라가서 겹치기 때문에 어색해져서요!

2023-03-02 03:14 UTC, ccdkk reviewed
고생하셨습니다!!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = KBPH295XX9;
p2;
팀 지워주세요!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    private let tableviewRefreshControl = UIRefreshControl()
오옷 refreshControl까지..! 디테일 미쳤네용

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        NotificationCenter.default.addObserver(
p3;
등록된 observer를 remove해주는 곳도 필요할 것 같아요! 보통 deinit에서 하더라구요

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    }
p2;
optional을 바인딩 해주기 위해 if let을 사용했는데 최종 타입캐스팅은 [CommentList]? 인 optional값으로 되어서 의도 파악이 어려운 것 같습니다. 애초에 self.commenData가 옵셔널 값이여서 대입하는데에는 타입캐스팅만 해주어도 될 것 같아요.

or 옵셔널 바인딩을 위한 것이라면 [CommentList] 로 타입캐스팅을 하고 
그 아래 reloadData나, setupTotalListNumberLabel()도 if let 구문 안에 넣는 것은 어떨까요? 
data값이 nil인 경우에 실행되지 않아도 되는 함수들 같아서요!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +            name: NSNotification.Name(rawValue: "load"),
p3;
Notification.Name + extension에서 observer name을 관리하는 것은 어떤가요?!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/DetailContentView.swift
> +            return ["밴드상세", "방명록"]
q
타임라인은 왜 삭제 되었나요?

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/DetailContentView.swift
> +    init(type: DetailTopInfoType, bandData: BandInformationVO ) {
p3;
입력받을 때 어떤 type에 대한 명시가 있으면 좋을 것 같아요.
detailTopInfoType? 그대로 사용해도 될 것 같고..

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +        if self.commentTextView.text.isEmpty == false {
p4;
isEmpty가 Bool 값이니 !self.commentTextView.text.isEmpty로 하는 것은 어떤가요? 가독성이 살짝 떨어질까요?

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +            queryURLComponent?.queryItems = [memberIdQuery,bandIdQuery,content]
p3;
element 사이에 간격 부탁드려요!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +            let request = NSMutableURLRequest(url: url,
p2;
요거는 URLRequest 공식문서인데요 swift 코드를 작성하는 경우에는 NSMutableURLRequest보다 URLRequest 사용을 권장하더라구요! cachePolicy와 timeoutInterval 등등 사용법을 똑같아서 URLRequest로만 바꾸면 될 것 같아요. 
<img width="839" alt="스크린샷 2023-02-28 오후 4 44 01" src="https://user-images.githubusercontent.com/91456952/221786812-506e28c7-9234-4970-9c5d-e41e3685c98f.png">

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
p3;
swift 함수 네이밍에서 get사용을 지양하더라구요. 그냥 bandData()는 어떨까요?

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +            let dataTask = URLSession.shared.dataTask(with: request as URLRequest,
p2;
NSMutableURLRequest를 URLRequest로 바꾸시면 여기서 타입캐스팅이 필요 없습니다!

2023-03-02 03:14 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                    print(error?.localizedDescription ?? "error case occured")
p2;
바로 아래에서 error를 사용하는 것 같은데 에러처리를 if let으로 해주는 것은 어떤가요?

2023-03-02 03:17 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    @objc func refreshTable(refresh: UIRefreshControl) {
감사합니다! 반영했습니다!
1850e4bdda898c194509c8edd21d2d0f741f0d11

2023-03-02 03:17 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +    @objc func TapAddCommentButton() {
감사합니다! 반영했습니다!
1850e4bdda898c194509c8edd21d2d0f741f0d11

2023-03-02 03:18 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
댓글을 POST한 후 밴드의  BandDetailViewController()의 getBandData()를 실행시켜서
추가된 댓글을 가져오기 위해 사용되었습니다!

2023-03-02 03:29 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                "Notion-Version": "2022-06-28",
앗 그러네여 header는 잘 살펴보지않았네요..ㅠㅠ 
감사합니다! 반영했습니다!

074efef26996491fca8e48c9c4386250770dbadc

2023-03-02 03:36 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
> p3; swift 함수 네이밍에서 get사용을 지양하더라구요. 그냥 bandData()는 어떨까요?

뭔가 함수명 앞에 동사가 없는게 어색한데 찾아보니 인스턴스를 리턴할때는 동사없이 명사만 쓰는 경우도 있군요
아니면 fetch를 사용해도 좋을것같은데 `bandData()`,  `fetchBandData()` 둘 중에 어떤 함수명이 나으신가요?!

<img width="400" alt="image" src="https://user-images.githubusercontent.com/103012104/222324624-2d370aac-4137-4cdd-b805-426eb77a31b4.png">

출처 : https://soojin.ro/blog/english-for-developers-swift

2023-03-02 04:57 UTC, ccdkk commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            view.addSubview(bandTopInfoView)
q;
혹시 데이터를 넣어준 다음에 뷰를 그려줘야하는 이유가 있을까요? 
didSet으로 reload를 다시 해줘서 꼭 Task에 없어도 되더라구요.

2023-03-02 04:57 UTC, ccdkk commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +    lazy var bandDetailContentView: DetailContentView? = nil
optional로 주신 이유가 궁금합니다.

2023-03-02 05:11 UTC, GODNOEL commented on GetARock/GetARock.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = KBPH295XX9;
넵 반영했습니다!
6c2a5c410acd431b493a9400e1d624577ae53b62

2023-03-02 05:12 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/DetailContentView.swift
> +            return ["밴드상세", "방명록"]
타임라인이 사실 모여락 히스토리 기능이라서
1차 배포때 모여락이 빠지게된 현 상황에서는 아예빼고 진행한 후
2차에 모여락기능이 들어가면 들어가는게 자연스러운거 같아 빼고 진행하게 되었습니다!

2023-03-02 06:04 UTC, GODNOEL commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            view.addSubview(bandTopInfoView)
넵 반영했습니다! 그리고 이제 didSet이 적용되서 Task에 layout을 잡지않아도 
Comment 목록이 불러와져서 해당 부분도 수정 진행했습니다!

24e58700748e234bd2697c2560c2851aac719646

2023-03-02 06:09 UTC, GODNOEL commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            view.addSubview(bandTopInfoView)
아 처음에 didSet으로 테이블뷰를 리로드 하는 기능을 구현하기 전에
밴드 정보를 Get해와서 테이블뷰를 그릴때, 밴드 정보를 DetailContentView뷰에 넘기고 
CommentListView에 넘겨 테이블 뷰를 그려야햇는데
그 부분이 동시적으로 진행되어 먼저 테이블뷰가 그려지고 데이터가 들어와 빈 목록이 노출되
Task로 순서대로 들어갈 수 있게 작성한 거였습니다! 

근데 지금 밴드정보가 들어오면 테이블뷰가 리로드되게 구현해서 지금은  데이크 말씀대로  없어도될것같네요!
예리한 충고 감사합니다!

24e58700748e234bd2697c2560c2851aac719646

2023-03-02 06:11 UTC, GODNOEL commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +    lazy var bandDetailContentView: DetailContentView? = nil
위와 같은이유로  TASK에서 처리하기 위해  미리 선언해두고 
밴드 데이터가 들어오면 정보를 넘기려고 optional로 선언한거였는데
아래 커밋에서 변경했습니다!
감사합니다!

24e58700748e234bd2697c2560c2851aac719646

2023-03-02 06:30 UTC, GODNOEL reviewed
> p3;
> 등록된 observer를 remove해주는 곳도 필요할 것 같아요! 보통 deinit에서 하더라구요

@ccdkk 
감사합니다! 반영했습니다!
1bcf67f6f27ac743c58d3b9e476061eea735a41a

2023-03-02 06:46 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    }
오옷..! 감사합니다 데이크 센세의 예리한 지적..!
아래 커밋에 수정했습니다! 감사합니다! 

d553a0575ef84e545242e939b77fa35cb5b7b804

2023-03-02 07:19 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +            name: NSNotification.Name(rawValue: "load"),
오옷 이런곳이 있었군요! 반영했습니다!
감사합니다!

eb5b796712d5192e6d812a1f25d09cb917d11d20

2023-03-02 07:38 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/DetailContentView.swift
> +    init(type: DetailTopInfoType, bandData: BandInformationVO ) {
넵 반영했습니다! 
그리고 원래는 각 상세페이지의 top(밴드명과 위치 나오는 부분)도 enum으로 사용하려다가 변경했는데
그 잔재로 타입명이 `DetailTopInfoType`으로 되어있었던것같네요
상세페이지의 타입이라는 의미인 `DetailInfoType`로 변경도 같이 진행했습니다!

f9a646230108b47b3c829ab390c1c909a14142f9

2023-03-02 07:43 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +        if self.commentTextView.text.isEmpty == false {
개인적으로 가독성이 살짝 떨어지는데
먼가 코드가 짧아져서 깔끔해보이는것같긴하네요!
반영했습니다! 감사합니다!

272445a6b97403981c58410a18d92858b80db5f1

2023-03-02 07:47 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +            let request = NSMutableURLRequest(url: url,
오오오옷 감사합니다 또하나 배워가네요..!
공식문서 백과사전 데이크...👍
반영했습니다 감사합니다!

8de47cde323f972c282f752c6811b928fabfbfe0

2023-03-02 07:47 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +            let dataTask = URLSession.shared.dataTask(with: request as URLRequest,
아래커밋에 함께 반영했습니다!
감사합니다!

8de47cde323f972c282f752c6811b928fabfbfe0

2023-03-02 11:09 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
함수명으로는 fetch가 좀 더 나아보이네요!

2023-03-04 02:14 UTC, ccdkk commented
@GODNOEL 
~~지금 branch에서 보고 있는데 decoding에러가 뜨네용..전엔 안그랬는데 혹시 수정사항이 있을까요?~~
잘 되는거 확인 완료

2023-03-06 05:53 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
fetch 좋네용!

2023-03-06 07:56 UTC, ccdkk approved these changes
고생하셨습니다!!!

2023-03-07 00:56 UTC, Rookie0031 approved these changes

2023-03-07 07:56 UTC, compuTasha commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            print("응답 내용 : \(response)")
p2;

머지 전에 불필요한 프린트문 및 주석은 삭제 부탁드려요!

2023-03-07 08:00 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/WriteCommentTextView.swift
> +                await BandDetailViewController().getBandData()
넵 수정했습니다! 
7f8914a102eb2fa71704e0ae5752fb5c14426a67

2023-03-07 08:02 UTC, compuTasha commented on GetARock/GetARock/Global/Network/Model/BandInformationVO.swift
> +}
p4;

같은 코드가 `NotificationListVO`에도 있던데 공통으로 쓰이는거면 파일을 따로 만들어서 관리하는 게 좋을 것 같아요..!

2023-03-07 08:11 UTC, compuTasha commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +    }
p3;

필요없는 메소드라면 삭제 부탁드립니당

2023-03-07 08:12 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
디테일 쏘굿이네요

2023-03-07 08:15 UTC, GODNOEL commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +            print("응답 내용 : \(response)")
통신 요청에서 프린트문은 서버와 통신이 되는지 확인할 수 있는 용도로 냅두는거 어떠신가요?
추후 뷰들 연결되었을때 해당 뷰에 데이터가 잘 들어오고 있는지 확인할 수 있을것같아서요!
하트문자는 삭제했습니다!

27e37e9568efae31088e63b7bbd46a683f15d63a

2023-03-07 08:15 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    }
해결돼서 다행이지만 아직 왜 기존 방법이 안 되는 건지 못 찾아서 아쉽네요..ㅠㅠ

init 함수 포함해서 이 부분이 PR에 있는 코드에서 조금 변경된 것 같아요! 
PR에 있는 코드도 수정 부탁드립니당

2023-03-07 08:19 UTC, GODNOEL commented on GetARock/GetARock/Global/Network/Model/BandInformationVO.swift
> +}
넵 삭제했습니다!
0805772250ce3f5663afe4ac5abeac5ae5b38857

2023-03-07 08:22 UTC, GODNOEL commented on GetARock/GetARock/Screens/BandDetail/BandDetailViewController.swift
> +    }
넵 감사합니다!
c5a6d4c752a33ccbb1805e21e4a6ecdb16fb1c86

2023-03-07 08:24 UTC, compuTasha approved these changes
말 안 듣는 델리게이트 친구 혼쭐내느라 너무 고생하셨습니다..

2023-03-07 08:26 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/CommentListView.swift
> +    }
넵!!

2023-03-07 08:26 UTC, merged