[Design] 1-3 공통컴포넌트인 SelectCollectionView를 구현하였습니다.
extreme-rock/GetARock-iOS pull request #54
Opened 2023-01-28 02:26 UTC by ccdkk

## 관련 이슈
- Close #45 

## 작업 내용
- cell의 layout이 글자수에 따라 width가 변하는 경우, 글자수와 관계없이 width가 고정인 경우가 있습니다.
이를 `WidthOption`를 통해 구분했습니다. 
```Swift
enum WidthOption {
    case fixed
    case flexable
}
```
따라서 SelectCollectionView를 Init할 때 `WidthOption`, `items`, `width` 총 3개의 파라미터를 받는데요, `WidthOption`에 따라 width에 입력해주는 값에 차이가 있습니다.
- `fixed`: 만들고자하는 박스의 width 값을 입력합니다.
<img width="200" alt="스크린샷 2023-01-28 오전 11 14 11" src="https://user-images.githubusercontent.com/91456952/215236863-6acb3903-7368-4dce-b805-e82218a5df4b.png">

- `flexable`: 만들고자 하는 박스 내부의 Label로 부터 leading, trailing 까지의 간격을 입력합니다.
<img width="743" alt="스크린샷 2023-01-28 오전 11 20 03" src="https://user-images.githubusercontent.com/91456952/215237122-5fe90077-a905-46ce-9012-77220d6f5dc2.png">

- 추후 선택된 값은 아래 메소드를 통해서 가져올 수 있습니다.
```Swift
    func selectedItem() -> String {
        let selectedIndex = collectionView.indexPathsForSelectedItems?.first
        return items[selectedIndex?.item ?? 0]
    }
```

## 리뷰 노트
- 현재는 WidthState에 따른 cell의 배경색이 다르기 때문에 WidthOption에 따라 특정 색을 주었는데, 다른 색상으로 확장될 계획이 있으면 color값을 입력받아도 좋을 것 같습니다. 디자이너님의 고견 부탁드려요! @GODNOEL 
- 변수명이 적절한지.
- 넣어주는 width값이 `WidthOption`에 따라 차이가 있는데 헷갈리지는 않는지.

## 테스트 방법
LandingVC에 아래코드 복붙!
```Swift
    
    let test = SelectCollectionView(widthOption: .fixed, items: ["20대 미만","20 대", "60대 이상", "30 대", "40 대"], widthSize: 100)
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .black
        view.addSubview(test)
        
        test.constraint(top: view.topAnchor,
                        leading: view.leadingAnchor,
                        bottom: view.bottomAnchor,
                        trailing: view.trailingAnchor,
                        padding: UIEdgeInsets(top: 300, left: 10, bottom: 0, right: 0))
        
    }
```

## 스크린샷
|fixedWidth|flexableWidth|
|:---|:---|
|![Simulator Screen Recording - iPhone 14 Pro - 2023-01-28 at 11 23 36](https://user-images.githubusercontent.com/91456952/215237381-32068a3e-db06-4250-95bc-27ce57ae72a1.gif)|![Simulator Screen Recording - iPhone 14 Pro - 2023-01-28 at 11 23 59](https://user-images.githubusercontent.com/91456952/215237384-b674346f-7f65-4349-8a59-7b578e17db83.gif)|

2023-01-28 14:00 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
p3;

WidthState라는 이름이 직관적이지 못한 것 같습니다..
WidthState를 isFlexible 이라는 네이밍의 Bool 타입 변수로 선언하고
true/false 값에 따라 분기처리를 하는 건 어떨까요?

2023-01-28 14:03 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        }
q;

flexibleWidth 인 경우에도 widthSize를 설정해줘야 하나요??

2023-01-28 14:05 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +}
p4;

indexPathsForSelectedItems가 nil을 return하는 경우에 대비해 String? 으로 리턴하는 게 좋을 것 같스빈다..!

2023-01-28 15:40 UTC, Rookie0031 requested changes
## 고생하셨습니다! 👍

 여기서도 compositional Layout을 사용하셨군요! 이번거도 요긴하게 잘 가져다 쓰겠습니다 ㅎㅎㅎ

### 버튼 탭시 배경 관련 버그
 버튼을 탭하고 자세히 보면 뒷 배경은 사각형 형태로 보라색 처리가 되어있는데 관련 코드 수정부탁드리곘습니다!
<img width="132" alt="image" src="https://user-images.githubusercontent.com/103009135/215275283-fc7bf502-5194-492e-a915-9d3e26686bd1.png">

### 선택취소 기능
버튼 탭하고 한번 더 누르면 비활성화되는 선택취소 기능은 딱히 필요없을까요?? 이게 쓰이는 항목들은 전부 필수항목이라 딱히 필요없을거 같기도해요

2023-01-28 15:40 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        group.interItemSpacing = .fixed(5)
p1;

제가 이 컬렉션뷰를 사용할 때는 간격이 7이더라구요!! 그래서 itemSpace도 init할 때 파라미터로 넣을 수 있게 해주면 감사하겠슴다!!
<img width="200" alt="image" src="https://user-images.githubusercontent.com/103009135/215274057-5e489460-3698-4521-8b7a-481885163701.png">

2023-01-28 15:40 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
p5; 
그러게요 여기는 네이밍이 어렵네요 ㅋㅋㅋ... 

    enum WidthOption {
        case fixed
        case flexible
    }

저는 이 정도도 괜찮지않을까 싶네요?

2023-01-28 15:40 UTC, Rookie0031 commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        collectionView.register(SelectCollectionViewCell.self, forCellWithReuseIdentifier: "SelectCollectionViewCell")
p5;

제 어프룹이 늦어져서 identifier를 문자열 처리하셧군요...😂 이전 컬렉션뷰 PR 머지하시고 className으로 고고합시다!

2023-01-29 05:19 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
WidthOption 괜찮네요. isFlexible의 false로 fixed라는게 잘 떠오른다면 그것도 좋은 것 같아요. 
흠 고민되네용

2023-01-29 05:20 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        }
flexibleWidth인 경우 설정해주는 widthSizes는 pr에 써놓은 것 처럼 label로 부터 leading, trailing까지의 거리입니다.
공통컴포넌트를 보면 두 가지의 경우가 있어서 이렇게 구현하였습니다.
<img width="401" alt="스크린샷 2023-01-29 오후 2 20 38" src="https://user-images.githubusercontent.com/91456952/215306670-c28d44ad-c460-4013-85bd-090be760b63f.png">

2023-01-29 05:21 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        group.interItemSpacing = .fixed(5)
헉 생각지도 못하고 있었네요. 감사합니당[9c36fc0](https://github.com/extreme-rock/GetARock-iOS/pull/54/commits/9c36fc008f011c36f08bd4075ca1ca18533e506e)에서 반영하였습니다.

2023-01-29 05:22 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +}
좋아요!! [47decea](https://github.com/extreme-rock/GetARock-iOS/pull/54/commits/47deceaffeb2928ae47a5b1964c688f9db96a801)에서 반영하였습니다.

2023-01-29 05:26 UTC, ccdkk commented
@Rookie0031 
> 버튼을 탭하고 자세히 보면 뒷 배경은 사각형 형태로 보라색 처리가 되어있는데 관련 코드 수정부탁드리곘습니다!

허걱.. 매의눈을 가지고 계시군요.. 큰일 날 뻔했네요.. 감사합니다. [1d4601d](https://github.com/extreme-rock/GetARock-iOS/pull/54/commits/1d4601d0c7c163638aad0923b8955bf0c71cd8fb)에서 반영하였습니다!!

> 버튼 탭하고 한번 더 누르면 비활성화되는 선택취소 기능은 딱히 필요없을까요?? 이게 쓰이는 항목들은 전부 필수항목이라 딱히 필요없을거 같기도해요

다시 확인해봤는데 확실히 아직까지는 필수요소에서만 사용되는 것 같아요. 추후에 선택 요소에도 활용하게 된다면 그 때 추가하겠습니다!

2023-01-29 12:47 UTC, compuTasha commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
저는 둘다 좋아요~~

2023-01-30 01:39 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
[a3a6be8](https://github.com/extreme-rock/GetARock-iOS/pull/54/commits/a3a6be8c2719306d919029c02d62b8fa0c88844e)에서 WidthOption으로 반영하였습니다!

2023-01-30 01:40 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        collectionView.register(SelectCollectionViewCell.self, forCellWithReuseIdentifier: "SelectCollectionViewCell")
[0cdb9a8](https://github.com/extreme-rock/GetARock-iOS/pull/54/commits/0cdb9a8d6cc79830dc409b5b7f90f7425b1e9d43)에서 반영완료!

2023-01-30 01:51 UTC, GODNOEL approved these changes
## 데이크 고생하셨습니당!
역시 컬렉션뷰 마스터답게 깔끔한 코드 인상적이네요!

2023-01-30 01:51 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +
저도 둘다 조하여

2023-01-30 01:51 UTC, GODNOEL commented on GetARock/GetARock/Screens/Landing/LandingViewController.swift
> +class LandingViewController: BaseViewController {
q5;
머지할때 LandingViewController 원복해주세용!

2023-01-30 01:51 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/SelectCollectionViewCell.swift
> +    }
프로퍼티 옵저버로 선택 시 색 바꿔주는거 좋네용

2023-01-30 01:51 UTC, GODNOEL commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        }
q5;
설명드렸어야했는데 디자인할때  남자/ 여자 같이 선택지가 2개인 경우, 
각셀의 너비는 핸드폰 기기에 따라 양옆 마진 16px를 뺀 전체너비에서 
셀 간의 간격 10px을 띌 수 있는 크기로 계산되서 보여진다고 생각했는데
(아이폰 미니같은 화면이 작은 곳에서는 너비가 고정되면 셀이 2줄로 나뉠 수 있을것같아서..!)

일단 입력 받아서 고정 값으로 가도 좋을 것 같아요!

2023-01-30 01:57 UTC, compuTasha approved these changes

2023-01-30 02:11 UTC, ccdkk commented on GetARock/GetARock/Global/UIComponent/SelectCollectionView.swift
> +        }
처음 고려할 때는 flexible로 생각했었는데 노엘 말씀처럼 남자 여자는 fixedWidth로 가도 될 것 같네요. 
`UIScreen.main.width - 32 - 10`로 width를 주면 될 것 같아요!

2023-01-30 02:53 UTC, Rookie0031 approved these changes

2023-01-30 02:55 UTC, merged

2023-02-01 02:37 UTC, compuTasha commented
github action 무료 사용 시간을 다 써서 build test 실패라고 떠있는 PR 입니다..^^  

<img width="146" alt="image" src="https://user-images.githubusercontent.com/51108729/215503307-97974b05-a1cc-4b67-95cb-7605dd94d591.png">